version: '2'

services:
  tc-frontend:
    image: node:10-alpine
    working_dir: /app
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    command: "npm run start:docker"

  tc-backend:
    image: node:10-alpine
    working_dir: /app
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - ./backend:/app
    environment: 
      NODE_ENV: 'docker'
    command: "npm run start:docker"
    depends_on:
      - tc-database

  tc-database:
    image: postgres
    ports: 
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  dbdata: 